steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', 'golang.org/x/tools/cmd/cover']
  env:
  - GOPATH=.
- name: 'gcr.io/cloud-builders/go'
  args: ['get', 'github.com/mattn/goveralls']
  env:
  - GOPATH=.
- name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v', '-bench=.',  '-covermode=count', '-coverprofile=coverage.out', './...']
  env:
  - GOPATH=.
