steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', 'golang.org/x/tools/cmd/cover']
- name: 'gcr.io/cloud-builders/go'
  args: ['get', 'github.com/mattn/goveralls']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v', '-bench=.',  '-covermode=count', '-coverprofile=coverage.out', './...']
- name: 'ubuntu'
  args: ['$GOPATH/bin/goveralls', '-coverprofile=coverage.out', '-repotoken', '$COVERALLS_TOKEN']
  env:
  - CI_NAME=cloudbuild
  - CI_BUILD_NUMBER=$BUILD_ID
  - CI_BUILD_URL=https://console.cloud.google.com/cloud-build/builds?project=$PROJECT_ID
  - CI_BRANCH=$BRANCH_NAME
